# Generated by Django 6.0.5 on 2026-05-24 11:55

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_usereventlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Poster or banner image for the event.', null=True, upload_to=events.models.get_event_image_path),
        ),
    ]
