# Generated by Django 6.0.5 on 2026-06-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, help_text='Will be stored as a hashed/encrypted value for security.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, choices=[('first_pet', 'What was the name of your first pet?'), ('mother_maiden', "What is your mother's maiden name?"), ('first_school', 'What was the name of your first school?'), ('birth_city', 'In what city were you born?'), ('favorite_movie', 'What is your favorite movie?')], max_length=50, null=True),
        ),
    ]
